In [1]:
import requests
import pandas as pd
import numpy as np

In [2]:
url="https://api.github.com/repos/pandas-dev/pandas/issues"
resp=requests.get(url)
type(resp)

requests.models.Response

In [3]:
resp

In [4]:
data=resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42718',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42718/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42718/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42718/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/42718',
  'id': 952351519,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0Njk2NTYxMDY4',
  'number': 42718,
  'title': 'TST: Fixed doctest in Styler.to_latex #42672',
  'user': {'login': 'willie3838',
   'id': 21048435,
   'node_id': 'MDQ6VXNlcjIxMDQ4NDM1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/21048435?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/willie3838',
   'html_url': 'https://github.com/willie3838',
   'followers_url': 'https://api.github.com/users/willie3838/followers',
   'following_url': 'https://api.github.com/users/willie3838/following{/other_user}',
   'gists_url': 'https://api.github.com/users/willie3838/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/willie3838/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/willie3838/subscriptions',
   'organizations_url': 'https://api.github.com/users/willie3838/orgs',
   'repos_url': 'https://api.github.com/users/willie3838/repos',
   'events_url': 'https://api.github.com/users/willie3838/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/willie3838/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-07-25T20:38:18Z',
  'updated_at': '2021-07-26T00:57:58Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/42718',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/42718',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/42718.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/42718.patch'},
  'body': '- [x] closes #42672 \r\n- [x] tests added / passed\r\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n- [x] whatsnew entry\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42717',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42717/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42717/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42717/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/42717',
  'id': 952346905,
  'node_id': 'MDU6SXNzdWU5NTIzNDY5MDU=',
  'number': 42717,
  'title': 'DEPR: Remove Int64Index, UInt64Index, Float64Index and Index._is_backward_compat_public_numeric_index',
  'user': {'login': 'topper-123',
   'id': 26364415,
   'node_id': 'MDQ6VXNlcjI2MzY0NDE1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/26364415?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/topper-123',
   'html_url': 'https://github.com/topper-123',
   'followers_url': 'https://api.github.com/users/topper-123/followers',
   'following_url': 'https://api.github.com/users/topper-123/following{/other_user}',
   'gists_url': 'https://api.github.com/users/topper-123/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/topper-123/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/topper-123/subscriptions',
   'organizations_url': 'https://api.github.com/users/topper-123/orgs',
   'repos_url': 'https://api.github.com/users/topper-123/repos',
   'events_url': 'https://api.github.com/users/topper-123/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/topper-123/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 87485152,
    'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Deprecate',
    'name': 'Deprecate',
    'color': '5319e7',
    'default': False,
    'description': 'Functionality to remove in pandas'},
   {'id': 1218227310,
    'node_id': 'MDU6TGFiZWwxMjE4MjI3MzEw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Index',
    'name': 'Index',
    'color': 'e99695',
    'default': False,
    'description': 'Related to the Index class or subclasses'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/42',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/42',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/42/labels',
   'id': 1945020,
   'node_id': 'MDk6TWlsZXN0b25lMTk0NTAyMA==',
   'number': 42,
   'title': '2.0',
   'description': '',
   'creator': {'login': 'jreback',
    'id': 953992,
    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',
    'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/jreback',
    'html_url': 'https://github.com/jreback',
    'followers_url': 'https://api.github.com/users/jreback/followers',
    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',
    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',
    'organizations_url': 'https://api.github.com/users/jreback/orgs',
    'repos_url': 'https://api.github.com/users/jreback/repos',
    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/jreback/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 11,
   'closed_issues': 4,
   'state': 'open',
   'created_at': '2016-08-16T13:21:24Z',
   'updated_at': '2021-07-25T20:09:12Z',
   'due_on': '2022-06-30T07:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2021-07-25T20:09:03Z',
  'updated_at': '2021-07-25T20:09:47Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': 'In Pandas 2.0 NumericIndex should be the default numerical index and `Int64Index`, `UInt64Index` and `Float64Index` should be removed. See #41153 & 41272 for more discussion.\r\n\r\n#41153 adds an internal attribute `_is_backward_compat_public_numeric_index` to the `Index` class (and its numeric child classes). This is only used to keep track of whether an index is a `NumericIndex` or one of its child indexes (`Int64Index`, `UInt64Index` and `Float64Index`) in order to maintain backwards compatability in Pandas 1.x. It will not be needed in pandas 2.0 after the child classes are removed and should removed in pandas 2.0 also.',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42716',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42716/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42716/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42716/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/42716',
  'id': 952339928,
  'node_id': 'MDU6SXNzdWU5NTIzMzk5Mjg=',
  'number': 42716,
  'title': 'CI: xarray upgrade to 0.19 broke CI Checks pipeline',
  'user': {'login': 'phofl',
   'id': 61934744,
   'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/phofl',
   'html_url': 'https://github.com/phofl',
   'followers_url': 'https://api.github.com/users/phofl/followers',
   'following_url': 'https://api.github.com/users/phofl/following{/other_user}',
   'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions',
   'organizations_url': 'https://api.github.com/users/phofl/orgs',
   'repos_url': 'https://api.github.com/users/phofl/repos',
   'events_url': 'https://api.github.com/users/phofl/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/phofl/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Related to Continuous Integration'},
   {'id': 527603109,
    'node_id': 'MDU6TGFiZWw1Mjc2MDMxMDk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dependencies',
    'name': 'Dependencies',
    'color': 'd93f0b',
    'default': False,
    'description': 'Related to pandas required and optional  dependencies'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-07-25T19:28:26Z',
  'updated_at': '2021-07-25T23:08:29Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'body': 'Xarray was recently upgrade from 0.18.2 to 0.19 in our ci. This broke the checks pipeline\r\n\r\nPassing:\r\nhttps://github.com/pandas-dev/pandas/runs/3155104841\r\n\r\nFailing:\r\nhttps://github.com/pandas-dev/pandas/pull/42713/checks?check_run_id=3155841275',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42715',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42715/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42715/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42715/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/42715',
  'id': 952339725,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0Njk2NTUyMjY2',
  'number': 42715,
  'title': 'Pin xarray to get ci passing',
  'user': {'login': 'phofl',
   'id': 61934744,
   'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/phofl',
   'html_url': 'https://github.com/phofl',
   'followers_url': 'https://api.github.com/users/phofl/followers',
   'following_url': 'https://api.github.com/users/phofl/following{/other_user}',
   'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions',
   'organizations_url': 'https://api.github.com/users/phofl/orgs',
   'repos_url': 'https://api.github.com/users/phofl/repos',
   'events_url': 'https://api.github.com/users/phofl/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/phofl/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Related to Continuous Integration'},
   {'id': 527603109,
    'node_id': 'MDU6TGFiZWw1Mjc2MDMxMDk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dependencies',
    'name': 'Dependencies',
    'color': 'd93f0b',
    'default': False,
    'description': 'Related to pandas required and optional  dependencies'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-07-25T19:27:06Z',
  'updated_at': '2021-07-25T19:38:07Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/42715',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/42715',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/42715.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/42715.patch'},
  'body': '- [x] xref #42716\r\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n\r\nPinning until fixed',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42714',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42714/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42714/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42714/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/42714',
  'id': 952336756,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0Njk2NTQ5OTM2',
  'number': 42714,
  'title': 'PERF/REGR: isin slowdown for masked type',
  'user': {'login': 'mzeitlin11',
   'id': 37011898,
   'node_id': 'MDQ6VXNlcjM3MDExODk4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/37011898?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mzeitlin11',
   'html_url': 'https://github.com/mzeitlin11',
   'followers_url': 'https://api.github.com/users/mzeitlin11/followers',
   'following_url': 'https://api.github.com/users/mzeitlin11/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mzeitlin11/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mzeitlin11/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mzeitlin11/subscriptions',
   'organizations_url': 'https://api.github.com/users/mzeitlin11/orgs',
   'repos_url': 'https://api.github.com/users/mzeitlin11/repos',
   'events_url': 'https://api.github.com/users/mzeitlin11/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mzeitlin11/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 1817503692,
    'node_id': 'MDU6TGFiZWwxODE3NTAzNjky',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/NA%20-%20MaskedArrays',
    'name': 'NA - MaskedArrays',
    'color': '8cc645',
    'default': False,
    'description': 'Related to pd.NA and nullable extension arrays'},
   {'id': 8935311,
    'node_id': 'MDU6TGFiZWw4OTM1MzEx',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance',
    'name': 'Performance',
    'color': 'a10c02',
    'default': False,
    'description': 'Memory or execution speed performance'},
   {'id': 32815646,
    'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression',
    'name': 'Regression',
    'color': 'e11d21',
    'default': False,
    'description': 'Functionality that used to work in a prior pandas version'},
   {'id': 2468482981,
    'node_id': 'MDU6TGFiZWwyNDY4NDgyOTgx',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/isin',
    'name': 'isin',
    'color': 'fef2c0',
    'default': False,
    'description': ''}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/88',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/88',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/88/labels',
   'id': 6998423,
   'node_id': 'MI_kwDOAA0YD84AasmX',
   'number': 88,
   'title': '1.3.2',
   'description': 'on-merge: backport to 1.3.x',
   'creator': {'login': 'simonjayhawkins',
    'id': 13159005,
    'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
    'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/simonjayhawkins',
    'html_url': 'https://github.com/simonjayhawkins',
    'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
    'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
    'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
    'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
    'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
    'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 20,
   'closed_issues': 2,
   'state': 'open',
   'created_at': '2021-07-23T08:57:52Z',
   'updated_at': '2021-07-25T19:09:04Z',
   'due_on': '2021-08-15T07:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2021-07-25T19:08:47Z',
  'updated_at': '2021-07-25T19:48:51Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/42714',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/42714',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/42714.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/42714.patch'},

In [5]:
perfect=pd.DataFrame(data)
perfect

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,pull_request,body,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42718,952351519,MDExOlB1bGxSZXF1ZXN0Njk2NTYxMDY4,42718,TST: Fixed doctest in Styler.to_latex #42672,...,None,1,2021-07-25T20:38:18Z,2021-07-26T00:57:58Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #42672 \r\n- [x] tests added / pa...,None
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42717,952346905,MDU6SXNzdWU5NTIzNDY5MDU=,42717,"DEPR: Remove Int64Index, UInt64Index, Float64I...",...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-07-25T20:09:03Z,2021-07-25T20:09:47Z,None,CONTRIBUTOR,None,NaN,In Pandas 2.0 NumericIndex should be the defau...,None
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42716,952339928,MDU6SXNzdWU5NTIzMzk5Mjg=,42716,CI: xarray upgrade to 0.19 broke CI Checks pip...,...,None,1,2021-07-25T19:28:26Z,2021-07-25T23:08:29Z,None,MEMBER,None,NaN,Xarray was recently upgrade from 0.18.2 to 0.1...,None
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42715,952339725,MDExOlB1bGxSZXF1ZXN0Njk2NTUyMjY2,42715,Pin xarray to get ci passing,...,None,0,2021-07-25T19:27:06Z,2021-07-25T19:38:07Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] xref #42716\r\n- [x] Ensure all linting ...,None
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42714,952336756,MDExOlB1bGxSZXF1ZXN0Njk2NTQ5OTM2,42714,PERF/REGR: isin slowdown for masked type,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-07-25T19:08:47Z,2021-07-25T19:48:51Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,"- [x] Ensure all linting tests pass, see [here...",None
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42713,952326799,MDExOlB1bGxSZXF1ZXN0Njk2NTQyMzE1,42713,Use find_stack_level for SettingWithCopyWarning,...,None,0,2021-07-25T18:09:31Z,2021-07-25T18:09:41Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,"- [x] Ensure all linting tests pass, see [here...",None
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42710,952304656,MDExOlB1bGxSZXF1ZXN0Njk2NTI1MTc3,42710,DOC use pepy-tech badge in README instead of c...,...,None,0,2021-07-25T16:02:56Z,2021-07-25T16:02:56Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,cf Gitter conversation\r\n\r\n- [ ] closes #xx...,None
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42709,952304441,MDExOlB1bGxSZXF1ZXN0Njk2NTI1MDEw,42709,updated empty() docstrings,...,None,6,2021-07-25T16:01:53Z,2021-07-25T18:28:32Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes ##42697\r\n\r\n,None
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42708,952271131,MDU6SXNzdWU5NTIyNzExMzE=,42708,RLS: 1.3.2,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-07-25T13:07:34Z,2021-07-25T13:07:34Z,None,MEMBER,None,NaN,Tracking issue for the 1.3.2 release. Currentl...,None
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42706,952230357,MDExOlB1bGxSZXF1ZXN0Njk2NDY4MDU5,42706,DOC: NumericIndex,...,None,0,2021-07-25T09:03:51Z,2021-07-25T14:16:12Z,None,CONTRIBUTOR,None,{'url': 'https://api.github.com/repos/pandas-d...,Adding docs etc. for #41153.\r\n\r\nThis depen...,None
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42705,952229983,MDExOlB1bGxSZXF1ZXN0Njk2NDY3Nzky,42705,TST: fixed eng_formatter doctest for #42671,...,None,4,2021-07-25T09:01:34Z,2021-07-25T17:47:52Z,None,CONTRIBUTOR,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #42671\r\n- [x] tests added / pas...,None
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42704,952178690,MDExOlB1bGxSZXF1ZXN0Njk2NDI4OTI0,42704,PERF: unstack,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-07-25T01:47:47Z,2021-07-25T14:39:07Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,```\r\nfrom asv_bench.benchmarks.reshape impor...,None
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42702,952101757,MDExOlB1bGxSZXF1ZXN0Njk2MzcwNzA2,42702,PERF: DataFrame constructor,...,None,0,2021-07-24T16:06:21Z,2021-07-24T16:06:21Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx\r\n- [ ] tests added / pass...,None
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42701,952080605,MDExOlB1bGxSZXF1ZXN0Njk2MzU1MTAy,42701,TST: fix read_stata doctest #42670,...,None,3,2021-07-24T13:57:49Z,2021-07-25T13:58:45Z,None,CONTRIBUTOR,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #42670\r\n- [x] tests added / pas...,None
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42700,952074081,MDExOlB1bGxSZXF1ZXN0Njk2MzUwMzA4,42700,TST: Solution to doctest error in _parse_latex...,...,{'url': 'https://api.github.com/repos/pandas-d...,3,2021-07-24T13:18:05Z,2021-07-25T17:39:56Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,The following commit fixes the doctext in _par...,None
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42697,952006580,MDU6SXNzdWU5NTIwMDY1ODA=,42697,DOC: description for Series.empty is referenci...,...,None,8,2021-07-24T05:44:10Z,2021-07-25T15:33:47Z,None,NONE,None,NaN,#### Location of the documentation\r\n\r\nhttp...,None
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42690,951853162,MDExOlB1bGxSZXF1ZXN0Njk2MTczOTQ2,42690,REGR: ValueError raised when both prefix and n...,...,None,0,2021-07-23T19:45:48Z,2021-07-25T16:23:15Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #42387 \r\n- [ ] tests added / pa...,None
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42688,951546763,MDU6SXNzdWU5NTE1NDY3NjM=,42688,BUG: value_counts and nunique behave different...,...,None,2,2021-07-23T12:43:48Z,2021-07-25T15:39:58Z,None,NONE,None,NaN,- [x] I have checked that this issue has not a...,None
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42684,951465925,MDExOlB1bGxSZXF1ZXN0Njk1ODQ3NzIy,42684,Fixed bug: Dataframe.sort_values not raising V...,...,{'url': 'https://api.github.com/repos/pandas-d...,2,2021-07-23T10:46:25Z,2021-07-25T14:03:38Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #41634\r\n- [x] tests added / pas...,None
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42683,951402101,MDU6SXNzdWU5NTE0MDIxMDE=,42683,ENH: Performance optimization for pd.merge int...,...,None,0,2021-07-23T09:19:57Z,2021-07-23T09:30:04Z,None,NONE,None,NaN,#### Is your feature request related to a prob...,None
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42682,951342796,MDU6SXNzdWU5NTEzNDI3OTY=,42682,BUG: pd.concat coerces ints to floats if empty...,...,None,0,2021-07-23T07:58:47Z,2021-07-23T07:58:47Z,None,NONE,None,NaN,- I have checked that this issue has not alrea...,None
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42674,951040271,MDU6SXNzdWU5NTEwNDAyNzE=,42674,TST: Fix doctest in _parse_latex_table_styles,...,None,4,2021-07-22T20:44:27Z,2021-07-23T23:52:04Z,None,MEMBER,None,NaN,# tl;dr\r\n\r\nFix the next doctest error:\r\n...,None
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42673,951038890,MDU6SXNzdWU5NTEwMzg4OTA=,42673,TST: Fix doctest in _parse_latex_header_span,...,None,5,2021-07-22T20:43:02Z,2021-07-24T17:12:21Z,None,MEMBER,None,NaN,# tl;dr\r\n\r\nFix the next doctest error:\r\n...,None
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42672,951037690,MDU6SXNzdWU5NTEwMzc2OTA=,42672,TST: Fix doctest in Styler.to_latex,...,None,2,2021-07-22T20:41:46Z,2021-07-25T16:00:19Z,None,MEMBER,None,NaN,# tl;dr\r\n\r\nFix the next doctest error:\r\n...,None
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42671,951036580,MDU6SXNzdWU5NTEwMzY1ODA=,42671,TST: Fix doctest in EngFormatter,...,None,1,2021-07-22T20:40:34Z,2021-07-24T16:51:15Z,None,MEMBER,None,NaN,# tl;dr\r\n\r\nFix the next doctest error:\r\n...,None
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42670,951034833,MDU6SXNzdWU5NTEwMzQ4MzM=,42670,TST: Fix doctest in read_stata,...,None,1,2021-07-22T20:38:46Z,2021-07-24T13:01:45Z,None,MEMBER,None,NaN,# tl;dr\r\n\r\nFix the next doctest error:\r\n...,None
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42669,950927753,MDExOlB1bGxSZXF1ZXN0Njk1Mzk4NTM1,42669,ENH: Add BytesIOWrapper,...,None,0,2021-07-22T18:14:53Z,2021-07-24T13:23:22Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #39383\r\n- [ ] tests added / pas...,None
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42668,950864201,MDExOlB1bGxSZXF1ZXN0Njk1MzQ1NzM0,42668,BUG: compute.use_numexpr option not respected,...,None,1,2021-07-22T16:56:28Z,2021-07-25T18:15:38Z,None,CONTRIBUTOR,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #32556\r\n- [x] tests added / pas...,None
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42667,950841454,MDExOlB1bGxSZXF1ZXN0Njk1MzI2ODEy,42667,Update frame.py,...,None,2,2021-07-22T16:26:37Z,2021-07-24T22:28:53Z,None,NONE,None,{'url': 'https://api.github.com/repos/pandas-d...,Added an example to the reorder_levels functio...,None
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42665,950757614,MDExOlB1bGxSZXF1ZXN0Njk1MjU2NDk0,42665,TST: Test Loc to set Multiple Items to multipl...,...,None,3,2021-07-22T14:54:56Z,2021-07-23T16:00:50Z,None,CONTRIBUTOR,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #25594\r\n- [x] tests added / pas...,None

In [6]:
data[0]["user"]["node_id"]

'MDQ6VXNlcjIxMDQ4NDM1'

In [7]:
perfect.to_csv(r"C:\Users\ADMIN\Desktop\Json.csv")

In [8]:
date=pd.date_range("04/12/2021",periods=7)
date

DatetimeIndex(['2021-04-12', '2021-04-13', '2021-04-14', '2021-04-15',
               '2021-04-16', '2021-04-17', '2021-04-18'],
              dtype='datetime64[ns]', freq='D')

In [9]:
ts=pd.Series(np.arange(7),index=date)
ts

2021-04-12    0
2021-04-13    1
2021-04-14    2
2021-04-15    3
2021-04-16    4
2021-04-17    5
2021-04-18    6
Freq: D, dtype: int32

In [10]:
frame=pd.DataFrame(ts)
frame

            0
2021-04-12  0
2021-04-13  1
2021-04-14  2
2021-04-15  3
2021-04-16  4
2021-04-17  5
2021-04-18  6

In [11]:
val=np.array([1,2,np.nan,3,4,5,6,7])
val

array([ 1.,  2., nan,  3.,  4.,  5.,  6.,  7.])

In [12]:
6+np.nan

nan

In [13]:
7*np.nan

nan

In [14]:
np.nansum(val)

28.0

In [15]:
val2=pd.Series([1,2,np.nan,4,5,None])
val2

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [16]:
val2

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [17]:
val2.fillna(value="--")

0     1
1     2
2    --
3     4
4     5
5    --
dtype: object

In [18]:
val2

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [19]:
val2

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [20]:
val2.fillna(method="bfill")

0    1.0
1    2.0
2    4.0
3    4.0
4    5.0
5    NaN
dtype: float64

In [21]:
val2.fillna(method="ffill")

0    1.0
1    2.0
2    2.0
3    4.0
4    5.0
5    5.0
dtype: float64

In [22]:
val2

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [23]:
val3=pd.read_excel(r"C:\Users\ADMIN\Desktop\companydata.xlsx")

In [24]:
val3

      regiment company     name  pretestscore  posttestscore  class cabin
0   Nighthawks     1st   sanjay             1              0      1   A01
1   Nighthawks     1st  sandeep             0              1      2   A02
2   Nighthawks     2nd    sonia             1              0      3   A03
3   Nighthawks     2nd   sunita             0              1      1   B04
4     Dragoons     1st  parkash             1              0      2   B05
5     Dragoons     1st     sonu             0              1      3   B06
6     Dragoons     2nd    vinod             0              0      1   C07
7     Dragoons     2nd   mukesh             1              0      1   C08
8       Scouts     1st   harish             1              0      2   NaN
9       Scouts     1st   sushma             1              0      3   NaN
10      Scouts     2nd    suman             1              0      3   NaN
11      Scouts     2nd     baby             0              1      3   NaN

In [25]:
val4=pd.DataFrame(val3)
val4

      regiment company     name  pretestscore  posttestscore  class cabin
0   Nighthawks     1st   sanjay             1              0      1   A01
1   Nighthawks     1st  sandeep             0              1      2   A02
2   Nighthawks     2nd    sonia             1              0      3   A03
3   Nighthawks     2nd   sunita             0              1      1   B04
4     Dragoons     1st  parkash             1              0      2   B05
5     Dragoons     1st     sonu             0              1      3   B06
6     Dragoons     2nd    vinod             0              0      1   C07
7     Dragoons     2nd   mukesh             1              0      1   C08
8       Scouts     1st   harish             1              0      2   NaN
9       Scouts     1st   sushma             1              0      3   NaN
10      Scouts     2nd    suman             1              0      3   NaN
11      Scouts     2nd     baby             0              1      3   NaN

In [26]:
val3.set_index(["regiment","company"],drop=True)

                       name  pretestscore  posttestscore  class cabin
regiment   company
Nighthawks 1st       sanjay             1              0      1   A01
           1st      sandeep             0              1      2   A02
           2nd        sonia             1              0      3   A03
           2nd       sunita             0              1      1   B04
Dragoons   1st      parkash             1              0      2   B05
           1st         sonu             0              1      3   B06
           2nd        vinod             0              0      1   C07
           2nd       mukesh             1              0      1   C08
Scouts     1st       harish             1              0      2   NaN
           1st       sushma             1              0      3   NaN
           2nd        suman             1              0      3   NaN
           2nd         baby             0              1      3   NaN

In [27]:
val3

      regiment company     name  pretestscore  posttestscore  class cabin
0   Nighthawks     1st   sanjay             1              0      1   A01
1   Nighthawks     1st  sandeep             0              1      2   A02
2   Nighthawks     2nd    sonia             1              0      3   A03
3   Nighthawks     2nd   sunita             0              1      1   B04
4     Dragoons     1st  parkash             1              0      2   B05
5     Dragoons     1st     sonu             0              1      3   B06
6     Dragoons     2nd    vinod             0              0      1   C07
7     Dragoons     2nd   mukesh             1              0      1   C08
8       Scouts     1st   harish             1              0      2   NaN
9       Scouts     1st   sushma             1              0      3   NaN
10      Scouts     2nd    suman             1              0      3   NaN
11      Scouts     2nd     baby             0              1      3   NaN

In [28]:
val3

      regiment company     name  pretestscore  posttestscore  class cabin
0   Nighthawks     1st   sanjay             1              0      1   A01
1   Nighthawks     1st  sandeep             0              1      2   A02
2   Nighthawks     2nd    sonia             1              0      3   A03
3   Nighthawks     2nd   sunita             0              1      1   B04
4     Dragoons     1st  parkash             1              0      2   B05
5     Dragoons     1st     sonu             0              1      3   B06
6     Dragoons     2nd    vinod             0              0      1   C07
7     Dragoons     2nd   mukesh             1              0      1   C08
8       Scouts     1st   harish             1              0      2   NaN
9       Scouts     1st   sushma             1              0      3   NaN
10      Scouts     2nd    suman             1              0      3   NaN
11      Scouts     2nd     baby             0              1      3   NaN

In [29]:
val4

      regiment company     name  pretestscore  posttestscore  class cabin
0   Nighthawks     1st   sanjay             1              0      1   A01
1   Nighthawks     1st  sandeep             0              1      2   A02
2   Nighthawks     2nd    sonia             1              0      3   A03
3   Nighthawks     2nd   sunita             0              1      1   B04
4     Dragoons     1st  parkash             1              0      2   B05
5     Dragoons     1st     sonu             0              1      3   B06
6     Dragoons     2nd    vinod             0              0      1   C07
7     Dragoons     2nd   mukesh             1              0      1   C08
8       Scouts     1st   harish             1              0      2   NaN
9       Scouts     1st   sushma             1              0      3   NaN
10      Scouts     2nd    suman             1              0      3   NaN
11      Scouts     2nd     baby             0              1      3   NaN

In [30]:
data100=pd.read_excel(r"C:\Users\ADMIN\Desktop\companydata.xlsx")
data100.head()

     regiment company     name  pretestscore  posttestscore  class cabin
0  Nighthawks     1st   sanjay             1              0      1   A01
1  Nighthawks     1st  sandeep             0              1      2   A02
2  Nighthawks     2nd    sonia             1              0      3   A03
3  Nighthawks     2nd   sunita             0              1      1   B04
4    Dragoons     1st  parkash             1              0      2   B05

In [31]:
new_survived=pd.Categorical(data100["posttestscore"])
new_survived=new_survived.rename_categories(["Dead","Leave"])
new_survived.describe()

            counts     freqs
categories
Dead             8  0.666667
Leave            4  0.333333

In [32]:
new_class=pd.Categorical(data100["class"])
new_class=new_class.rename_categories(["Class 1","Class 2","Class 3"])
new_class.describe()

            counts     freqs
categories
Class 1          4  0.333333
Class 2          3  0.250000
Class 3          5  0.416667

In [33]:
data100["class"].unique()

array([1, 2, 3], dtype=int64)

In [34]:
data100["cabin"].unique()

array(['A01', 'A02', 'A03', 'B04', 'B05', 'B06', 'C07', 'C08', nan],
      dtype=object)

In [35]:
data100["class"]=new_class

In [36]:
data100

      regiment company     name  pretestscore  posttestscore    class cabin
0   Nighthawks     1st   sanjay             1              0  Class 1   A01
1   Nighthawks     1st  sandeep             0              1  Class 2   A02
2   Nighthawks     2nd    sonia             1              0  Class 3   A03
3   Nighthawks     2nd   sunita             0              1  Class 1   B04
4     Dragoons     1st  parkash             1              0  Class 2   B05
5     Dragoons     1st     sonu             0              1  Class 3   B06
6     Dragoons     2nd    vinod             0              0  Class 1   C07
7     Dragoons     2nd   mukesh             1              0  Class 1   C08
8       Scouts     1st   harish             1              0  Class 2   NaN
9       Scouts     1st   sushma             1              0  Class 3   NaN
10      Scouts     2nd    suman             1              0  Class 3   NaN
11      Scouts     2nd     baby             0              1  Class 3   NaN

In [37]:
data100["Status"]=new_survived

In [38]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status
0,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead
1,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead
3,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave
4,Dragoons,1st,parkash,1,0,Class 2,B05,Dead
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave
6,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead
7,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead
8,Scouts,1st,harish,1,0,Class 2,NaN,Dead
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave

In [39]:
new_char=data100["cabin"].astype(str)
new_line=np.array([cabin[0] for cabin in new_char])
new_line=pd.Categorical(new_line)
new_line.describe()

            counts     freqs
categories
A                3  0.250000
B                3  0.250000
C                2  0.166667
n                4  0.333333

In [40]:
data100["Cabin Status"]=new_line

In [41]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status
0,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A
1,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A
3,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B
4,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B
6,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C
7,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C
8,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n

In [42]:
val3

      regiment company     name  pretestscore  posttestscore  class cabin
0   Nighthawks     1st   sanjay             1              0      1   A01
1   Nighthawks     1st  sandeep             0              1      2   A02
2   Nighthawks     2nd    sonia             1              0      3   A03
3   Nighthawks     2nd   sunita             0              1      1   B04
4     Dragoons     1st  parkash             1              0      2   B05
5     Dragoons     1st     sonu             0              1      3   B06
6     Dragoons     2nd    vinod             0              0      1   C07
7     Dragoons     2nd   mukesh             1              0      1   C08
8       Scouts     1st   harish             1              0      2   NaN
9       Scouts     1st   sushma             1              0      3   NaN
10      Scouts     2nd    suman             1              0      3   NaN
11      Scouts     2nd     baby             0              1      3   NaN

In [43]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status
0,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A
1,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A
3,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B
4,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B
6,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C
7,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C
8,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n

In [44]:
data100.set_index(["regiment","company"])

                       name  pretestscore  posttestscore    class cabin  \
regiment   company
Nighthawks 1st       sanjay             1              0  Class 1   A01
           1st      sandeep             0              1  Class 2   A02
           2nd        sonia             1              0  Class 3   A03
           2nd       sunita             0              1  Class 1   B04
Dragoons   1st      parkash             1              0  Class 2   B05
           1st         sonu             0              1  Class 3   B06
           2nd        vinod             0              0  Class 1   C07
           2nd       mukesh             1              0  Class 1   C08
Scouts     1st       harish             1              0  Class 2   NaN
           1st       sushma             1              0  Class 3   NaN
           2nd        suman             1              0  Class 3   NaN
           2nd         baby             0              1  Class 3   NaN

                   Status Cabin Status
regiment   company
Nighthawks 1st       Dead            A
           1st      Leave            A
           2nd       Dead            A
           2nd      Leave            B
Dragoons   1st       Dead            B
           1st      Leave            B
           2nd       Dead            C
           2nd       Dead            C
Scouts     1st       Dead            n
           1st       Dead            n
           2nd       Dead            n
           2nd      Leave            n

In [45]:
data100["Cabin Status"].value_counts()

n    4
B    3
A    3
C    2
Name: Cabin Status, dtype: int64

In [46]:
new_data = data100["Cabin Status"].unique()

In [47]:
new_data.value_counts()

A    1
B    1
C    1
n    1
dtype: int64

In [48]:
data100.set_index(["Cabin Status"])

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status
Cabin Status,,,,,,,,
A,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead
A,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave
A,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead
B,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave
B,Dragoons,1st,parkash,1,0,Class 2,B05,Dead
B,Dragoons,1st,sonu,0,1,Class 3,B06,Leave
C,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead
C,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead
n,Scouts,1st,harish,1,0,Class 2,NaN,Dead
n,Scouts,1st,sushma,1,0,Class 3,NaN,Dead
n,Scouts,2nd,suman,1,0,Class 3,NaN,Dead
n,Scouts,2nd,baby,0,1,Class 3,NaN,Leave

In [49]:
data100.set_index(["regiment","company","Cabin Status"])

                                    name  pretestscore  posttestscore  \
regiment   company Cabin Status
Nighthawks 1st     A              sanjay             1              0
                   A             sandeep             0              1
           2nd     A               sonia             1              0
                   B              sunita             0              1
Dragoons   1st     B             parkash             1              0
                   B                sonu             0              1
           2nd     C               vinod             0              0
                   C              mukesh             1              0
Scouts     1st     n              harish             1              0
                   n              sushma             1              0
           2nd     n               suman             1              0
                   n                baby             0              1

                                   class cabin Status
regiment   company Cabin Status
Nighthawks 1st     A             Class 1   A01   Dead
                   A             Class 2   A02  Leave
           2nd     A             Class 3   A03   Dead
                   B             Class 1   B04  Leave
Dragoons   1st     B             Class 2   B05   Dead
                   B             Class 3   B06  Leave
           2nd     C             Class 1   C07   Dead
                   C             Class 1   C08   Dead
Scouts     1st     n             Class 2   NaN   Dead
                   n             Class 3   NaN   Dead
           2nd     n             Class 3   NaN   Dead
                   n             Class 3   NaN  Leave

In [50]:
data100.to_csv(r"C:\Users\ADMIN\Desktop\myprocessdata.csv")

In [51]:
missing=np.where(data100["cabin"].isnull()==True)
missing

(array([ 8,  9, 10, 11], dtype=int64),)

In [52]:
len(missing[0])

4

In [53]:
index=np.where(data100["class"]==max(data100["class"]))
index

(array([ 2,  5,  9, 10, 11], dtype=int64),)

In [54]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status
0,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A
1,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A
3,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B
4,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B
6,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C
7,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C
8,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n

In [55]:
data100.loc[index]

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n

In [56]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status
0,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A
1,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A
3,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B
4,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B
6,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C
7,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C
8,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n

In [57]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status
0,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A
1,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A
3,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B
4,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B
6,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C
7,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C
8,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n

In [58]:
data100["Index"] =list(range(1,13))

In [59]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status,Index
0,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A,1
1,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A,2
2,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A,3
3,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B,4
4,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B,5
5,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B,6
6,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C,7
7,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C,8
8,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n,9
9,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n,10
10,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n,11
11,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n,12

In [60]:
data100.set_index(["Index"])

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status
Index,,,,,,,,,
1,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A
2,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A
3,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A
4,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B
5,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B
6,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B
7,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C
8,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C
9,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n
10,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n
11,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n
12,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n

In [61]:
data100.set_index([list(range(1,13))],inplace=True)

In [62]:
data100

,regiment,company,name,pretestscore,posttestscore,class,cabin,Status,Cabin Status,Index
1,Nighthawks,1st,sanjay,1,0,Class 1,A01,Dead,A,1
2,Nighthawks,1st,sandeep,0,1,Class 2,A02,Leave,A,2
3,Nighthawks,2nd,sonia,1,0,Class 3,A03,Dead,A,3
4,Nighthawks,2nd,sunita,0,1,Class 1,B04,Leave,B,4
5,Dragoons,1st,parkash,1,0,Class 2,B05,Dead,B,5
6,Dragoons,1st,sonu,0,1,Class 3,B06,Leave,B,6
7,Dragoons,2nd,vinod,0,0,Class 1,C07,Dead,C,7
8,Dragoons,2nd,mukesh,1,0,Class 1,C08,Dead,C,8
9,Scouts,1st,harish,1,0,Class 2,NaN,Dead,n,9
10,Scouts,1st,sushma,1,0,Class 3,NaN,Dead,n,10
11,Scouts,2nd,suman,1,0,Class 3,NaN,Dead,n,11
12,Scouts,2nd,baby,0,1,Class 3,NaN,Leave,n,12